# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'LicentaCosmic' do
    project 'LicentaCosmic.xcodeproj'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
# use_frameworks!

  # Pods for LicentaCosmic
  pod 'Google-Mobile-Ads-SDK'


#pod 'react-native-youtube', :path => '../node_modules/react-native-youtube'

end
